name: Firebase Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - functions/**
      - site/**
      - firebase**
      - firestore**
      - .firebaserc

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - run: npm ci --audit false

      - id: "auth"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_TWEETED_LINKS }}"

      - name: Deploy
        run: npm run deploy

  upload-debug-file:
    runs-on: ubuntu-latest
    needs: [deploy]
    if: always() && (needs.deploy.result == 'failure')
    steps:
      - uses: actions/upload-artifact
        with:
          name: "firebase-debug.log"
          path: "firebase-debug.log"
          retention-days: 1
