name: Firebase Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - functions/**
      - site/**
      - firebase**
      - firestore**
      - .firebaserc

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2

      - run: npm ci --audit false

      - name: Set service account
        run: echo ${{ secrets.FIREBASE_SERVICE_ACCOUNT_TWEETED_LINKS }} > "$HOME"/gcloud.json

      - name: Deploy
        run: GOOGLE_APPLICATION_CREDENTIALS="$HOME"/gcloud.json" npm run deploy
