name: Firebase Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - functions/**
      - site/**
      - firebase**
      - firestore**
      - .firebaserc

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - run: npm ci --audit false

      - id: "auth"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_TWEETED_LINKS }}"

      - name: Deploy
        run: npm run deploy
        # The following is useful to enable if the Firebase deploy is failing for mysterious reasons.
        # This outputs the debug log file to the Artifacts section of the workflow run.
        # continue-on-error: true

      # - uses: actions/upload-artifact@v2
      #   with:
      #     name: firebase-debug
      #     path: firebase-debug.log
      #     retention-days: 1
