name: Firebase Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - functions/**
      - site/**
      - firebase**
      - firestore**
      - .firebaserc

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2

      - run: npm ci --audit false

      - id: "auth"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_TWEETED_LINKS }}"

      - name: Deploy
        run: npm run deploy
